name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Inputing "Hello Universe!" Test
      id: inputing-hello-universe-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputing "Hello Universe!" Test
        setup-command: ''
        command: python3 regex_match_vowels/main.py
        input: Hello Universe!
        expected-output: "^e\\no\\nU\\ni\\ne\\ne\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INPUTING-HELLO-UNIVERSE-TEST_RESULTS: "${{steps.inputing-hello-universe-test.outputs.result}}"
      with:
        runners: inputing-hello-universe-test
